config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, :sessions, :events, :attendees

  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :attendee, class_name: User.name
  belongs_to :attended_event, class_name: Event.name

  validates :attendee_id, :attended_event_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendees, foreign_key: :attended_event_id
  has_many :invitees, through: :attendees, source: :attendee

  belongs_to :creator, class_name: User.name

  scope :past, -> { where('date < ?', Time.now) }
  scope :upcoming, -> { where('date >= ?', Time.now) }

  validates :date, :description, :name, :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id
  has_many :attendees, foreign_key: :attendee_id
  has_many :appointments, through: :attendees, source: :attended_event

  validates :name, :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    return unless session[:id]

    @current_user ||= User.find(session[:id])
  end

  def authorize
    redirect_to '/sessions/new' unless current_user
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def create
    @attendee = current_user.attendees.build
    @attendee.attended_event_id = params[:event_id]

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to event_path(@attendee.attended_event_id), notice: 'Attendee confirmed' }
        format.json { render :show, status: :created, location: @attendee }
      else
        format.html { render :new }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authorize

  def index
    @upcoming_events = Event.upcoming
    @past_events = Event.past
    query = 'SELECT "events".* FROM "events" INNER JOIN "attendees" ON "events"."id" = "attendees"."attended_event_id" '
    complement = 'WHERE NOT "attendees"."attendee_id" = '
    @events = Event.find_by_sql(query + complement + current_user.id.to_s)
    @appointments = current_user.appointments
  end

  def new
    @event = current_user.events.build
  end

  def show
    @event = Event.find(params[:id])
    @attend = if @event.invitees.exists?(current_user.id)
                true
              else
                false
              end
  end

  def appointment; end

  def cancel; end

  def create
    user = User.find(session[:id])
    @event = user.events.build(event_params)
    # @event = Event.new(event_params)
    # @event.user_id=session[:id]
    respond_to do |format|
      if @event.save
        format.html { redirect_to '/users', notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def destroy
    session[:id] = nil
    respond_to do |format|
      format.html { redirect_to '/sessions/new', notice: 'Login succesfully' }
    end
  end

  def create
    @login_user = User.new(session_params)

    if User.exists?(username: @login_user.username)
      usr = User.where(username: @login_user.username).limit(1).pluck

      session[:id] = usr[0][0]
      current_user
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'Login succesfully' }
      end
    else
      respond_to do |format|
        format.html { render :new }
      end

    end
  end

  private

  def session_params
    params.require(:user).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @user = session[:user]
    @events = Event.where(creator: current_user.id)
  end

  def login
    @user = User.new(params)
    # @current_user = User.find_by(username: @user.username)
    session[:user] = @user.username
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:id] = @user.id
        current_user
        format.html { redirect_to action: 'index', notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @your_events = Event.where(creator: current_user.id)
    @upcoming_events = current_user.appointments.upcoming
    @past_events = current_user.appointments.past
    @events = current_user.appointments
  end

  private

  def user_params
    params.require(:user).permit(:name, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Events<h1>

<h2>Upcoming events</h2>
<table>
<tr>
 <th>Name</th>
 <th>Location</th>
 <th>Date</th>
 <th>Description</th>
 <th>Creator</th>
</tr>

<% @upcoming_events.each do | event | %>
 <tr>
  <td><%= link_to event.name, event_path(event) %></td>
  <td><%= event.location %></td>
  <td><%= event.date %></td>
  <td><%= event.description %></td>
  <td><%= event.creator.name %></td>
 </tr>

<% end %>
</table>

<h2>Past events</h2>
<table>
<tr>
 <th>Name</th>
 <th>Location</th>
 <th>Date</th>
 <th>Description</th>
 <th>Creator</th>
</tr>

<% @past_events.each do | event | %>
 <tr>
  <td><%= link_to event.name, event_path(event) %></td>
  <td><%= event.location %></td>
  <td><%= event.date %></td>
  <td><%= event.description %></td>
  <td><%= event.creator.name %></td>
</tr>

<% end %>
</table>

<h2>All the events</h2>
<table>
<tr>
 <th>Name</th>
 <th>Location</th>
 <th>Date</th>
 <th>Description</th>
 <th>Creator</th>
</tr>

<% @events.each do | event | %>
 <tr>
  <td><%= link_to event.name, event_path(event) %></td>
  <td><%= event.location %></td>
  <td><%= event.date %></td>
  <td><%= event.description %></td>
  <td><%= event.creator.name %></td>
 </tr>

<% end %>
</table>

app/views/events/new.html.erb
<br>
<br>
<%= form_with(model: @event, local: true) do |form| %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label :date %>
      <%= form.date_field :date %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>

<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p><%= @event.description %></p>
<p>Creator:<%= @event.creator.name %></p>
<p>Location:<%= @event.location %></p>
<p>Date:<%= @event.date %></p>


<% if @attend %>
You are already register for this event
<% else %>
<%= button_to "I'll be there", attendees_path(:event_id => @event.id), :method => :post %>
<% end %>
<h2>Attendees</h2>
<table>
<tr>
 <th>Name</th>
</tr>

<% @event.invitees.each do | attendee | %>
 <tr>
  <td><%= attendee.name %></td>
 </tr>

<% end %>



</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if @current_user %>
     <ul>
 	<li><%= link_to @current_user.name, user_path(@current_user.id) %></li>
  	<li><%= link_to 'Logout', session_path(1),
          method: :delete  %></li>
        <li><%= link_to 'View events', events_path %></li>
        <li><%= link_to 'Create an event', new_event_path %></li>
     </ul>
<% else %>
 <%= link_to 'Login', new_session_path %>
 <%= link_to 'Sign Up', new_user_path %>
<% end %>
<br>
    <%= yield %>

  </body>
</html>

app/views/users/index.html.erb
<h1>Your Events</h1>
<table>
<tr>
 <th>Name</th>
 <th>Location</th>
 <th>Date</th>
 <th>Description</th>
 <th>Creator</th>
</tr>

<% @events.each do | event | %>
 <tr> 
  <td><%= link_to event.name, event_path(event) %></td>
  <td><%= event.location %></td>
  <td><%= event.date %></td> 
  <td><%= event.description %></td>
  <td><%= event.creator.name %></td>
 </tr>

<% end %>  
</table>    

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |form| %>

    <div class="field">  
      <%= form.label :name %>        
      <%= form.text_field :name %>   
    </div>

    <div class="field">
      <%= form.label :username %>    
      <%= form.text_field :username %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/users/show.html.erb
<br>
<h2>Your events</h2>
<table>
<tr>
 <th>Name</th>
 <th>Location</th>
 <th>Date</th>
 <th>Description</th>
 <th>Creator</th>
</tr>

<% @your_events.each do | event | %>
 <tr>
  <td><%= link_to event.name, event_path(event) %></td>
  <td><%= event.location %></td>
  <td><%= event.date %></td>
  <td><%= event.description %></td>
  <td><%= event.creator.name %></td>
 </tr>

<% end %>
</table>

<h2>Your appointments</h2>

<h3>Upcoming events</h3>
<table>
<tr>
 <th>Name</th>
 <th>Location</th>
 <th>Date</th>
 <th>Description</th>
 <th>Creator</th>
</tr>

<% @upcoming_events.each do | appointment | %>
 <tr>
  <td><%= appointment.name %></td>
  <td><%= appointment.location %></td>
  <td><%= appointment.date %></td>
  <td><%= appointment.description %></td>
  <td><%= appointment.creator.name %></td>
 </tr>

<% end %>
</table>


<h3>Past events</h3>
<table>
<tr>
 <th>Name</th>
 <th>Location</th>
 <th>Date</th>
 <th>Description</th>
 <th>Creator</th>
</tr>

<% @past_events.each do | appointment | %>
 <tr>
  <td><%= appointment.name %></td>
  <td><%= appointment.location %></td>
  <td><%= appointment.date %></td>
  <td><%= appointment.description %></td>
  <td><%= appointment.creator.name %></td>
 </tr>

<% end %>
</table>

app/views/users/sign_up.html.erb
<%= form_with(model: user, local: true) do |form| %>
     
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :username %>
      <%= form.text_area :username %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>